"Changes: Textures":
  - changed-files:
      - any-glob-to-any-file: 'src/main/resources/assets/textures/**/*.png'

"Changes: Structures":
  - changed-files:
      - any-glob-to-any-file:
          - 'src/main/resources/data/ait/structures/**/*.nbt'

#"Changes: UI":
#  - changed-files:
#      - any-glob-to-any-file: '**/*.xml*'

#"Changes: Shaders":
#  - changed-files:
#      - any-glob-to-any-file: '**/*.glsl'

"Changes: Audio":
  - changed-files:
      - any-glob-to-any-file: 'src/main/resources/assets/textures/**/*.ogg'

"Changes: No Java":
  - changed-files:
      # Equiv to any-glob-to-all as long as this has one matcher. If ALL changed files are not C# files, then apply label.
      - all-globs-to-all-files: "!src/main/java/**/*.java"