name: Append Changelog on PR Merge

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  append-changelog:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.BOT_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pyyaml

      - name: Append PR changelog
        env:
          GITHUB_EVENT_PATH: ${{ github.event_path }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python scripts/update_changelog.py

      - name: Commit and push changes using BOT_TOKEN
        env:
          TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          git config user.name "github-bot"
          git config user.email "bot@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "docs: update CHANGELOG for PR #${{ github.event.pull_request.number }}"
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }} HEAD:main
