name: "Labels: Size"
on: pull_request_target
permissions:
  pull-requests: write
  issues: write
  contents: write
jobs:
  size-label:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.draft == false }}
    outputs:
      label: ${{ steps.label.outputs.sizeLabel }}
    steps:
      - name: size-label
        id: label
        uses: "pascalgn/size-label-action@v0.5.5"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          # Custom size configuration
          sizes: >
            {
              "0": "XS",
              "10": "S",
              "100": "M",
              "1000": "L",
              "5000": "XL"
            }
      - if: ${{ contains(github.event.pull_request.labels.*.name, 'size/XS') || contains(github.event.pull_request.labels.*.name, 'size/S') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          url: ${{ github.event.pull_request.html_url }}
        run: |
          gh pr edit "$url" --add-reviewer Loqor,MaketendoDev,duzos
      - if: ${{ contains(github.event.pull_request.labels.*.name, 'size/M') || contains(github.event.pull_request.labels.*.name, 'size/L') || contains(github.event.pull_request.labels.*.name, 'size/XL') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          url: ${{ github.event.pull_request.html_url }}
        run: | 
          gh pr edit "$url" --add-reviewer DrTheodor,duzos